# Generated by Django 3.0.5 on 2020-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='image',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(),
        ),
    ]
