# Generated by Django 3.0.5 on 2020-05-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='email',
        ),
        migrations.AddField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(default='EELogo_Temp.png', upload_to='picx'),
        ),
    ]
