# Generated by Django 3.0.5 on 2020-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0002_auto_20200513_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.TextField(max_length=240),
        ),
    ]
