# Generated by Django 3.0.5 on 2020-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0003_auto_20200515_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='title',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default='Shall be responsible for ......'),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(default='Something Representative', max_length=22),
        ),
    ]
