# Generated by Django 3.0.5 on 2020-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0004_auto_20200515_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(default='Something Rep.', max_length=19),
        ),
    ]
