# Generated by Django 3.0.5 on 2020-05-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0006_auto_20200515_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lessfunc',
        ),
        migrations.RemoveField(
            model_name='team',
            name='morefunc',
        ),
    ]
