# Generated by Django 3.0.5 on 2020-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0007_auto_20200516_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.CharField(default='fa fa-icon', max_length=24),
        ),
    ]
