# Generated by Django 3.0.5 on 2020-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0008_team_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='icon',
        ),
        migrations.AddField(
            model_name='team',
            name='id_name',
            field=models.CharField(default='somethingrep', max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='lessfunc',
            field=models.TextField(default="'return less('<id>');'"),
        ),
        migrations.AddField(
            model_name='team',
            name='morefunc',
            field=models.TextField(default="'return more('<id>');'"),
        ),
    ]
