# Generated by Django 3.0.5 on 2020-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0009_auto_20200519_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lessfunc',
        ),
        migrations.RemoveField(
            model_name='team',
            name='morefunc',
        ),
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.CharField(default='fa fa-icon', max_length=24),
        ),
    ]
