# Generated by Django 3.0.5 on 2020-05-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourTeam', '0011_team_issenior'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isDuplicateDescription',
            field=models.BooleanField(default=False),
        ),
    ]
