# Generated by Django 3.0.5 on 2020-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication',
            field=models.DateTimeField(),
        ),
    ]
